name: build jar

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: branch-name
        id: branch-name
        uses: tj-actions/branch-names@v5
      - name: logs-branch-name
        run: |
          echo "Running on default: ${{ steps.branch-name.outputs.ref_branch }}"
      - name: docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}/${{ steps.branch-name.outputs.ref_branch }} .
      - name: logs-create-docker
        run: |
          echo "Create docker: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}/${{ steps.branch-name.outputs.ref_branch }}"
      - name: docker login 
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: docker push 
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}/${{ steps.branch-name.outputs.ref_branch }}
        
